const createEmailChangeAuth = (body) => axios.post(`${BASE_URL}/auth/change-email/`, body, getConfig())
const createPasswordChangeAuth = (body) => axios.post(`${BASE_URL}/auth/change-password/`, body, getConfig())
const getAuthCurrent = () => axios.get(`${BASE_URL}/auth/current-user/`, getConfig())
const createLoginAuth = (body) => axios.post(`${BASE_URL}/auth/login/`, body, getConfig())
const createAsLoginAuth = (body) => axios.post(`${BASE_URL}/auth/login-as/`, body, getConfig())
const getCmsContacts = () => axios.get(`${BASE_URL}/cms/contacts/`, getConfig())
const getCmsPages = () => axios.get(`${BASE_URL}/cms/pages/`, getConfig())
const createFieldFields = (body) => axios.post(`${BASE_URL}/fields/field/`, body, getConfig())
const getFieldsField = (slug) => axios.get(`${BASE_URL}/fields/field/${slug}/`, getConfig())
const updateFieldFields = (slug, body) => axios.put(`${BASE_URL}/fields/field/${slug}/`, body, getConfig())
const partialUpdateFieldFields = (slug, body) => axios.patch(`${BASE_URL}/fields/field/${slug}/`, body, getConfig())
const getFieldsField = (slug) => axios.delete(`${BASE_URL}/fields/field/${slug}/`, getConfig())
const getPaymentPayment = () => axios.get(`${BASE_URL}/payment/payment-methods/`, getConfig())
const createGuestProfiles = (body) => axios.post(`${BASE_URL}/profiles/guest/`, body, getConfig())
const createProfileProfiles = (body) => axios.post(`${BASE_URL}/profiles/profile/`, body, getConfig())
const getProfilesProfile = (id) => axios.get(`${BASE_URL}/profiles/profile/${id}/`, getConfig())
const getShelvesProduct = (product_slug) => axios.get(`${BASE_URL}/shelves/product/${product_slug}/`, getConfig())
const getShelvesProducts = () => axios.get(`${BASE_URL}/shelves/products/`, getConfig())
const getStoresList = () => axios.get(`${BASE_URL}/stores/list/`, getConfig())
const getStoresStore = (slug) => axios.get(`${BASE_URL}/stores/store/${slug}/`, getConfig())
const getSupportContacts = () => axios.get(`${BASE_URL}/support/contacts/`, getConfig())
const createVerificationRequestEmail = (body) => axios.post(`${BASE_URL}/auth/email/request-verification/`, body, getConfig())
const createVerifyEmailAuth = (body) => axios.post(`${BASE_URL}/auth/email/verify/`, body, getConfig())
const createVerificationRequestMobile = (body) => axios.post(`${BASE_URL}/auth/mobile/request-verification/`, body, getConfig())
const createVerifyMobileAuth = (body) => axios.post(`${BASE_URL}/auth/mobile/verify/`, body, getConfig())
const getCmsPages = (url) => axios.get(`${BASE_URL}/cms/pages/page/${url}/`, getConfig())
const getFieldsList = () => axios.get(`${BASE_URL}/fields/list/mine/`, getConfig())
const getFieldsList = () => axios.get(`${BASE_URL}/fields/list/template/`, getConfig())
const createChoiceTypesFields = (body) => axios.post(`${BASE_URL}/fields/types/choice/`, body, getConfig())
const createNumberTypesFields = (body) => axios.post(`${BASE_URL}/fields/types/number/`, body, getConfig())
const createAddCartOrders = (body) => axios.post(`${BASE_URL}/orders/cart/add/`, body, getConfig())
const createRemoveCartOrders = (body) => axios.post(`${BASE_URL}/orders/cart/remove/`, body, getConfig())
const createSetCartOrders = (body) => axios.post(`${BASE_URL}/orders/cart/set/`, body, getConfig())
const getOrdersCart = () => axios.get(`${BASE_URL}/orders/cart/show/`, getConfig())
const createCheckCouponOrders = (body) => axios.post(`${BASE_URL}/orders/coupon/check/`, body, getConfig())
const createCreateOrderOrders = (body) => axios.post(`${BASE_URL}/orders/order/create/`, body, getConfig())
const getOrdersOrder = (order_code) => axios.get(`${BASE_URL}/orders/order/${order_code}/details/`, getConfig())
const getOrdersOrder = () => axios.get(`${BASE_URL}/orders/order/list/`, getConfig())
const createAddAddressProfiles = (body) => axios.post(`${BASE_URL}/profiles/address/add/`, body, getConfig())
const getProfilesAddress = () => axios.get(`${BASE_URL}/profiles/address/list/`, getConfig())
const updateUpdateAddressProfiles = (address_slug, body) => axios.put(`${BASE_URL}/profiles/address/${address_slug}/update/`, body, getConfig())
const partialUpdateUpdateAddressProfiles = (address_slug, body) => axios.patch(`${BASE_URL}/profiles/address/${address_slug}/update/`, body, getConfig())
const getProfilesAddress = (address_slug) => axios.delete(`${BASE_URL}/profiles/address/${address_slug}/update/`, getConfig())
const updateEditProfileProfiles = (id, body) => axios.put(`${BASE_URL}/profiles/profile/${id}/edit/`, body, getConfig())
const partialUpdateEditProfileProfiles = (id, body) => axios.patch(`${BASE_URL}/profiles/profile/${id}/edit/`, body, getConfig())
const getShelvesCategories = () => axios.get(`${BASE_URL}/shelves/categories/list/`, getConfig())
const getShelvesCategory = (category_slug) => axios.get(`${BASE_URL}/shelves/category/${category_slug}/products/`, getConfig())
const createProductsCategoryShelves = (category_slug, body) => axios.post(`${BASE_URL}/shelves/category/${category_slug}/products/`, body, getConfig())
const createAddFavoritesShelves = (body) => axios.post(`${BASE_URL}/shelves/favorites/add/`, body, getConfig())
const createRemoveFavoritesShelves = (body) => axios.post(`${BASE_URL}/shelves/favorites/remove/`, body, getConfig())
const createSubProductsProductShelves = (product_slug, body) => axios.post(`${BASE_URL}/shelves/product/${product_slug}/sub_products/`, body, getConfig())
const getShelvesStore = (store_slug) => axios.get(`${BASE_URL}/shelves/store/${store_slug}/products/`, getConfig())
const createCreateTicketsSupport = (body) => axios.post(`${BASE_URL}/support/tickets/create/`, body, getConfig())
const getSupportTickets = () => axios.get(`${BASE_URL}/support/tickets/list/`, getConfig())
const getSupportTickets = (ticket_code) => axios.get(`${BASE_URL}/support/tickets/ticket/${ticket_code}/`, getConfig())
const createEmailResetPassword = (body) => axios.post(`${BASE_URL}/auth/password/reset/email/`, body, getConfig())
const createMobileResetPassword = (body) => axios.post(`${BASE_URL}/auth/password/reset/mobile/`, body, getConfig())
const createConfirmPasargadPayment = (body) => axios.post(`${BASE_URL}/payment/payment/pasargad/confirm/`, body, getConfig())
const createProcessPasargadPayment = (body) => axios.post(`${BASE_URL}/payment/payment/pasargad/process/`, body, getConfig())
const createRequestPasargadPayment = (body) => axios.post(`${BASE_URL}/payment/payment/pasargad/request/`, body, getConfig())
const createReplyTicketTickets = (ticket_code, body) => axios.post(`${BASE_URL}/support/tickets/ticket/${ticket_code}/reply/`, body, getConfig())
const createConfirmEmailReset = (body) => axios.post(`${BASE_URL}/auth/password/reset/email/confirm/`, body, getConfig())
const createConfirmMobileReset = (body) => axios.post(`${BASE_URL}/auth/password/reset/mobile/confirm/`, body, getConfig())
